### PR TITLE
360 bug readyplayermodule does not always show for players

### LINKED ISSUE #360: [BUG] MatchReadyModule does not always show for players
**Describe the bug**
During a XPEvo test match, the ready module did not show.

**To Reproduce**
1. Use command '...'
2. See error
or
1. Click on '...' widget
2. See error

**Expected behavior**

**Screenshots**

**Server environment (please complete the following information):**
 - TM2020 dedicated server version: [e.g. 2022-06-29]
 - OS [e.g. Windows, Linux]
 - EvoSC# version [use /version to find out the current version]

**Additional context**

### PR DESCRIPTION
**Pull request by snixtho**
Made the process of showing and handling the ready widget simpler and more robust.

### CODE REVIEW

File: src/Modules/MatchReadyModule/Controllers/ReadyCommandsController.cs [hunk 1]
```diff
@@ -8,24 +8,28 @@
...
-    public Task SetReadyAsync() => playerReady.SetPlayerReadyStatusAsync(Context.Player, true);
+    public Task SetReadyAsync() => readyService.SetPlayerReadyStatusAsync(Context.Player, true);
     
     [ChatCommand("unready", "Remove yourself as ready for the match.")]
     [CommandAlias("/ur")]
-    public Task SetUnreadyAsync() => playerReady.SetPlayerReadyStatusAsync(Context.Player, false);
+    [CommandAlias("/unrdy")]
+    public Task SetUnreadyAsync() => readyService.SetPlayerReadyStatusAsync(Context.Player, false);
 
     [ChatCommand("readytest", "Test the ready widget.")]
```
Comment (araszka) [inline src/Modules/MatchReadyModule/Controllers/ReadyCommandsController.cs:23]: Should the test command be merged?

File: src/Modules/MatchReadyModule/Events/MatchReadyEvents.cs [hunk 2]
```diff
@@ -10,5 +10,15 @@ public enum MatchReadyEvents
...
-    PlayerReadyChanged
+    PlayerReadyChanged,
+    
+    /// <summary>
+    /// Raised when the ready widget and service enabled.
+    /// </summary>
+    Enabled,
+    
+    /// <summary>
+    /// Raised when the ready widget and service enabled.
```
Comment (araszka) [inline src/Modules/MatchReadyModule/Events/MatchReadyEvents.cs:21]:
```suggestion
    /// Raised when the ready widget and service are disabled.
```

File: src/Modules/MatchReadyModule/Interfaces/IReadyService.cs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+{
+    public IEnumerable<IPlayer> ReadyPlayers { get; }
+    public IEnumerable<IPlayer> Players { get; }
+    public bool Enabled { get; }
+    public Task ResetAsync();
+    public Task AddPlayersAsync(params IPlayer[] players);
+    public Task SetPlayerReadyStatusAsync(IPlayer player, bool isReady);
+    public Task EnableAsync();
+    public Task DisableAsync();
+}
```
Comment (araszka) [inline src/Modules/MatchReadyModule/Interfaces/IReadyService.cs:54]: No doc comments on interface methods.

File: src/Modules/MatchReadyModule/Interfaces/IReadyManialinkService.cs [hunk 4]
```diff
@@ -0,0 +1,9 @@
+﻿using EvoSC.Common.Interfaces.Models;
+
+namespace EvoSC.Modules.Official.MatchReadyModule.Interfaces;
+
+public interface IReadyManialinkService
+{
+    public Task SendWidgetAsync();
+    public Task SendWidgetAsync(IPlayer player);
+}
```
Comment (araszka) [inline src/Modules/MatchReadyModule/Interfaces/IReadyManialinkService.cs:19]: No doc comments on interface methods.

File: src/Modules/MatchReadyModule/Interfaces/IReadyTrackerService.cs [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+    public bool Enabled { get; }
+    
+    public Task AddPlayerAsync(IPlayer player);
+    public Task RemovePlayerAsync(IPlayer player);
+    public Task AddReadyAsync(IPlayer player);
+    public Task RemoveReadyAsync(IPlayer player);
+    public Task ClearAsync();
+    public Task EnableAsync();
+    public Task DisableAsync();
+}
```
Comment (araszka) [inline src/Modules/MatchReadyModule/Interfaces/IReadyTrackerService.cs:72]: No doc comments on interface methods.

**Review by araszka — APPROVED** [review]

File: src/Modules/MatchReadyModule/Controllers/ReadyCommandsController.cs (hunk 1 above)
Comment (snixtho) [reply src/Modules/MatchReadyModule/Controllers/ReadyCommandsController.cs:23]: Yes, for now
